### ISSUE TITLE
The movie is not playing

### ISSUE THREAD

**Issue by Duna** [ruthwikkk/DRMOffline#1]
The movie is not playing. Can you share the command line where you get the encrypted video?

**Comment by ruthwikkk** [comment]
HI Duna,
This repo is created for tracking an issue. Please go through this so you will get the full context
[Read Here](https://github.com/google/ExoPlayer/issues/8237)

**Comment by Duna** [comment]
It would be nice for the community to share the requested info. Can you contact me directly dunatv@gmail.com ? I need some info
