### ISSUE TITLE
Key ID is not Base64

### ISSUE THREAD

**Issue by Duna** [ruthwikkk/DRMOffline#2]
`   playVideo("file:///android_asset/drm.mp4", "WEYnAyXfbYdWs5f7tTwH2w", "oIUkxBK-0IQSRqeHmSKGPg")`

oIUkxBK-0IQSRqeHmSKGPg - do contain forbidden char"-", which means is not base 64

Can you share the hex values also for `keyid` and `value`?

**Comment by Duna** [comment]
How did you encrypt the file?

**Comment by ruthwikkk** [comment]
> How did you encrypt the file?

Please refer https://github.com/google/ExoPlayer/issues/8237#issuecomment-730856435

**Comment by ruthwikkk** [comment]
> ` playVideo("file:///android_asset/drm.mp4", "WEYnAyXfbYdWs5f7tTwH2w", "oIUkxBK-0IQSRqeHmSKGPg")`
> 
> oIUkxBK-0IQSRqeHmSKGPg - do contain forbidden char"-", which means is not base 64
> 
> Can you share the hex values also for `keyid` and `value`?

Key Id --> 5846270325df6d8756b397fbb53c07db --> WEYnAyXfbYdWs5f7tTwH2w

Key Value --> a08524c412bed0841246a7879922863e --> oIUkxBK-0IQSRqeHmSKGPg

**Comment by Duna** [comment]
I used this convertor https://base64.guru/converter/encode/hex but shows me
different result

**Comment by ruthwikkk** [comment]
I just checked, Its correct but the format is base 64 url so = sign is optional. Ignore the == signs

**Comment by Duna** [comment]
Key Value --> a08524c412bed0841246a7879922863e --> oIUkxBK-0IQSRqeHmSKGPg

oIUkxBK+0IQSRqeHmSKGPg  - mine there is a + within, you have a - within
